name: security-action
on:
  push:
    branches: [feature/github-actions]

jobs:
  build:
    name: build maven
    runs-on: ubuntu-latest 
    steps:
    - uses: actions/checkout@v1 
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1 
      with:
        java-version: 1.8
    - name: build maven
      run: |
        mvn clean package install
        pwd
        ls -l  
    - name: salvando artefato
      uses: actions/upload-artifact@v3
      with:
          name: verademo.war
          path: target/verademo.war

  veracode-sca:
    runs-on: ubuntu-latest
    name: veracode sca

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        
      - name: veracode sca scan
        env: 
          SRCCLR_API_TOKEN: ${{ secrets.SRCCLR_API_TOKEN }}
        run: curl -sSL https://download.sourceclear.com/ci.sh | sh -s scan --update-advisor --uri-as-name --ref ${{ github.ref_name }}

  veracode_sast_sandbox_scan:
    name: veracode sandbox branch scan
    runs-on: ubuntu-latest
    needs: [ build ]
    
    steps:
      - name: Check out main branch
        uses: actions/checkout@v2
        
      - uses: actions/checkout@v2
      - name: get archive
        uses: actions/download-artifact@v3 
        with:
          name: verademo.war
          path: .

      - name: veracode sandbox branch scan
        uses: veracode/veracode-uploadandscan-action@0.2.6
        with:
          appname: 'verademo-java-web'
          createprofile: false
          filepath: 'verademo.war'
          vid: '${{ secrets.VERACODE_ID }}'
          vkey: '${{ secrets.VERACODE_KEY }}'
          createsandbox: 'true'
          sandboxname: "${{ github.ref }}"
          version: "${{ github.run_id }}"
          scantimeout: 0

  veracode_sast_policy_scan:
    name: veracode policy scan
    runs-on: ubuntu-latest
    needs: [ build, veracode_sast_sandbox_scan, veracode-sca ]
    
    steps:
      - name: Check out main branch
        uses: actions/checkout@v2
        
      - name: get archive
        uses: actions/download-artifact@v3 
        with:
          name: verademo.war
          path: .

      - name: Veracode Upload And Scan
        uses: veracode/veracode-uploadandscan-action@0.2.6
        with:
          appname: 'verademo-java-web'
          createprofile: false
          filepath: 'verademo.war'
          vid: '${{ secrets.VERACODE_ID }}'
          vkey: '${{ secrets.VERACODE_KEY }}'
          version: "${{ github.run_id }}"
          scantimeout: 0

  veracode_sast_pipeline_scan:
    runs-on: ubuntu-latest
    needs: [ build, veracode_sast_sandbox_scan ]
    name: veracode sast pipeline scan

    steps:
      - name: get archive
        uses: actions/download-artifact@v3 
        with:
          name: verademo.war
          path: .

      - name: pipeline-scan action step
        id: pipeline-scan
        uses: veracode/Veracode-pipeline-scan-action@v1.0.12
        with:
          vid: ${{ secrets.VERACODE_ID }}
          vkey: ${{ secrets.VERACODE_KEY }}
          file: "verademo.war"
          fail_build: "true"