name: security-action

on:
  push:
    branches: [dev]
  pull_request:
    branches: [dev]

  workflow_dispatch:

jobs:

  build:
    name: build maven
    runs-on: ubuntu-latest 
    steps:
    - uses: actions/checkout@v1 
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1 
      with:
        java-version: 1.8
    - name: build maven
      run: |
        mvn clean package install
        pwd
        ls -l  
    - name: salvando artefato
      uses: actions/upload-artifact@v3
      with:
          name: verademo.war
          path: target/verademo.war

 veracode-sast-sandbox-scan:
    runs-on: ubuntu-latest
    needs: [ build ]
    container:
      image: veracode/api-wrapper-java:latest
      options: --user root
    steps:
      - uses: actions/checkout@v2
      - name: get archive
        uses: actions/download-artifact@v3 
        with:
          name: verademo.war
          path: .
        
      - name: upload and branch scan
        run: |
          java -jar /opt/veracode/api-wrapper.jar -vid "${{ secrets.VERACODE_ID }}" -vkey "${{ secrets.VERACODE_KEY }}" -action UploadAndScan -createprofile true -appname "verademo-java-web" -version "${{ github.run_id }}" -filepath target/verademo.war -teams "{{ secrets.VERACODE_TEAM }}" -criticality "Medium" -createsandbox true -sandboxname "${{ github.ref }}" -deleteincompletescan 2 -lifecyclestage "InDevelopmentPreAlpha" 
  
  veracode-pipeline-scan:
    name: veracode sast pipeline scan
    runs-on: ubuntu-latest
    needs: [build, veracode-sast-sandbox-scan]
    container: 
      image: veracode/pipeline-scan:latest 
      options: --user root 
    steps:
      - uses: actions/checkout@v2
      - name: get archive
        uses: actions/download-artifact@v3 
        with:
          name: verademo.war
          path: .
      - name: veracode sast pipeline scan
        run: |
          java -jar /opt/veracode/pipeline-scan.jar -vid ${{ secrets.VERACODE_ID }} -vkey ${{ secrets.VERACODE_KEY }} -f target/verademo.war --project_name "verademo-java-web" -r ${{ github.ref }} -aid ${{ secrets.VERACODE_PROJECT_ID }} -ds "Development" || true
