name: security-action

on:
  push:
    branches: [dev]
  pull_request:
    branches: [dev]

  workflow_dispatch:

jobs:

  build:
    name: Build Maven
    runs-on: ubuntu-latest 
    steps:
    - uses: actions/checkout@v1 
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1 
      with:
        java-version: 1.8
    - name: Build with Maven 
      run: |
        mvn clean package install
        pwd
        ls -l  
    - name: salvando artefato
      uses: actions/upload-artifact@v3
      with:
          name: verademo.war
          path: target/verademo.war
